#!/bin/bash
set -ex

# Git repo
git clone https://github.com/mass-matrix/AMPL
cd AMPL/

# Get config file
yes | pfda download .env || true
. .env

# Docker
pfda download "ampl-${PLATFORM}-${ENV}.tar.gz" .
make load-docker
make jupyter-notebook
